# fly.toml app configuration file generated for chanhxe on 2023-09-24T05:25:45+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chanhxe"
primary_region = "sin"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_NAME = "ChanhXe"
  APP_ENV = "production"

  LOG_CHANNEL = "stack"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"

  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

  DB_CONNECTION = "pgsql"

  MAIL_MAILER = "failover"
  MAIL_FROM_ADDRESS = "khanglnse160108@fpt.edu.vn"

  CACHE_DRIVER = "redis"
  QUEUE_CONNECTION = "redis"

  REDIS_HOST = "lumethys-redis-prod.internal"
  REDIS_PORT = "6379"

  FILESYSTEM_DISK = "s3"
  AWS_ACCESS_KEY_ID = "AKIA5H6QXVIMG47AX2V7"
  AWS_DEFAULT_REGION = "ap-southeast-2"
  AWS_BUCKET = "chanhxe-prod"
  AWS_ENDPOINT = "https://s3.ap-southeast-2.amazonaws.com"
  AWS_USE_PATH_STYLE_ENDPOINT = "true"


  OCTANE_SERVER = "swoole"

  GOOGLE_DISTANCE_MATRIX_ENDPOINT = "https://maps.googleapis.com/maps/api/distancematrix/json"

  GOONG_DISTANCE_MATRIX_ENDPOINT = "https://rsapi.goong.io/DistanceMatrix"

  VNP_TMN_CODE = "J7MNCKOQ"
  VNP_URL = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  VNP_RETURN_URL_LOGIN = "https://chanhxemientay.vercel.app/user/order/"
  VNP_RETURN_URL_NOT_LOGIN = "https://chanhxemientay.vercel.app/tracking?code="
  VNP_API_URL = "http://sandbox.vnpayment.vn/merchant_webapi/merchant.html"
  API_URL = "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
  VNP_LOCALE = "vn"
  VNP_BANKCODE = "NCB"
  VNP_VERSION = "2.1.0"
  VNP_CURRCODE = "VND"

  CUSTOMER_FRONTEND_URL = "https://chanhxemientay.vercel.app"
  PARTNER_FRONTEND_URL = "https://chanhxepartner-k16.vercel.app"
  INTERNAL_FRONTEND_URL = "https://capstone-project-admin-tungvtse.vercel.app/"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app = ""
  cron = "cron -f"
  worker = "php artisan queue:listen"

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"
